# Dependencies


# Permalinks
permalink:        pretty

# Setup
title:            'Digital Maker Spaces: the Homer Multitext project '
tagline:          'Boston, 2018'
description:      ''
baseurl: '/HMT-SCS-2018/'



author:
  name:           'Neel Smith'

paginate:         5

links:
  - title: Github source for this site
    url: https://github.com/stephanieml/HMT-SCS-2018
    external: true
  - title: HMT home page
    url: http://www.homermultitext.org/
    external: true
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
